// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALwr8tXcfnRgC876Vgut4_alpHxG7J6q0',
    appId: '1:1094006570837:web:0a814261545779a25239dc',
    messagingSenderId: '1094006570837',
    projectId: 'tiddart-bad71',
    authDomain: 'tiddart-bad71.firebaseapp.com',
    storageBucket: 'tiddart-bad71.firebasestorage.app',
    measurementId: 'G-97L5SHQF90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9GgoCRf6Q99WJk87G4M-jwA374SmNwjg',
    appId: '1:1094006570837:android:6fff4ec5b5aebf0e5239dc',
    messagingSenderId: '1094006570837',
    projectId: 'tiddart-bad71',
    storageBucket: 'tiddart-bad71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuHdoToyF9DLJAQiw211_76ztFGJ3xvic',
    appId: '1:1094006570837:ios:e0820df4b8d82eb05239dc',
    messagingSenderId: '1094006570837',
    projectId: 'tiddart-bad71',
    storageBucket: 'tiddart-bad71.firebasestorage.app',
    iosBundleId: 'com.example.tiddart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuHdoToyF9DLJAQiw211_76ztFGJ3xvic',
    appId: '1:1094006570837:ios:e0820df4b8d82eb05239dc',
    messagingSenderId: '1094006570837',
    projectId: 'tiddart-bad71',
    storageBucket: 'tiddart-bad71.firebasestorage.app',
    iosBundleId: 'com.example.tiddart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALwr8tXcfnRgC876Vgut4_alpHxG7J6q0',
    appId: '1:1094006570837:web:ea7eb4f579eb96b95239dc',
    messagingSenderId: '1094006570837',
    projectId: 'tiddart-bad71',
    authDomain: 'tiddart-bad71.firebaseapp.com',
    storageBucket: 'tiddart-bad71.firebasestorage.app',
    measurementId: 'G-TWZEVHRJQ1',
  );
}
